services:
  postgres:
    image: postgres:15
    container_name: red_tetris_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "0.0.0.0:${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless stopped

volumes:
  pgdata:
